linters:
  enable-all: true
  fast: true

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  misspell:
    locale: US
  lll:
    line-length: 200
  funlen:
    lines: 140
    statements: 40
  govet:
    enable-all: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: Use zerolog instead.

issues:
  exclude-rules:
    - path: ".*_test.go"
      linters:
        - funlen
        - dupl
        - gocognit
        - maintidx
