// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package porter

import (
	"context"
	"io"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			GetPortFunc: func(ctx context.Context, unloc string) (*Port, error) {
//				panic("mock out the GetPort method")
//			},
//			PortsFromStreamFunc: func(ctx context.Context, data io.Reader) error {
//				panic("mock out the PortsFromStream method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// GetPortFunc mocks the GetPort method.
	GetPortFunc func(ctx context.Context, unloc string) (*Port, error)

	// PortsFromStreamFunc mocks the PortsFromStream method.
	PortsFromStreamFunc func(ctx context.Context, data io.Reader) error

	// calls tracks calls to the methods.
	calls struct {
		// GetPort holds details about calls to the GetPort method.
		GetPort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unloc is the unloc argument value.
			Unloc string
		}
		// PortsFromStream holds details about calls to the PortsFromStream method.
		PortsFromStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data io.Reader
		}
	}
	lockGetPort         sync.RWMutex
	lockPortsFromStream sync.RWMutex
}

// GetPort calls GetPortFunc.
func (mock *ServiceMock) GetPort(ctx context.Context, unloc string) (*Port, error) {
	if mock.GetPortFunc == nil {
		panic("ServiceMock.GetPortFunc: method is nil but Service.GetPort was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Unloc string
	}{
		Ctx:   ctx,
		Unloc: unloc,
	}
	mock.lockGetPort.Lock()
	mock.calls.GetPort = append(mock.calls.GetPort, callInfo)
	mock.lockGetPort.Unlock()
	return mock.GetPortFunc(ctx, unloc)
}

// GetPortCalls gets all the calls that were made to GetPort.
// Check the length with:
//
//	len(mockedService.GetPortCalls())
func (mock *ServiceMock) GetPortCalls() []struct {
	Ctx   context.Context
	Unloc string
} {
	var calls []struct {
		Ctx   context.Context
		Unloc string
	}
	mock.lockGetPort.RLock()
	calls = mock.calls.GetPort
	mock.lockGetPort.RUnlock()
	return calls
}

// PortsFromStream calls PortsFromStreamFunc.
func (mock *ServiceMock) PortsFromStream(ctx context.Context, data io.Reader) error {
	if mock.PortsFromStreamFunc == nil {
		panic("ServiceMock.PortsFromStreamFunc: method is nil but Service.PortsFromStream was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data io.Reader
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockPortsFromStream.Lock()
	mock.calls.PortsFromStream = append(mock.calls.PortsFromStream, callInfo)
	mock.lockPortsFromStream.Unlock()
	return mock.PortsFromStreamFunc(ctx, data)
}

// PortsFromStreamCalls gets all the calls that were made to PortsFromStream.
// Check the length with:
//
//	len(mockedService.PortsFromStreamCalls())
func (mock *ServiceMock) PortsFromStreamCalls() []struct {
	Ctx  context.Context
	Data io.Reader
} {
	var calls []struct {
		Ctx  context.Context
		Data io.Reader
	}
	mock.lockPortsFromStream.RLock()
	calls = mock.calls.PortsFromStream
	mock.lockPortsFromStream.RUnlock()
	return calls
}
