// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package portsfromstream

import (
	"context"
	"io"
	"porter"
	"sync"
)

// Ensure, that IngestorMock does implement Ingestor.
// If this is not the case, regenerate this file with moq.
var _ Ingestor = &IngestorMock{}

// IngestorMock is a mock implementation of Ingestor.
//
//	func TestSomethingThatUsesIngestor(t *testing.T) {
//
//		// make and configure a mocked Ingestor
//		mockedIngestor := &IngestorMock{
//			IngestFunc: func(ctx context.Context, data io.Reader, doer func(key string, chunk *porter.Port) error) error {
//				panic("mock out the Ingest method")
//			},
//		}
//
//		// use mockedIngestor in code that requires Ingestor
//		// and then make assertions.
//
//	}
type IngestorMock struct {
	// IngestFunc mocks the Ingest method.
	IngestFunc func(ctx context.Context, data io.Reader, doer func(key string, chunk *porter.Port) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Ingest holds details about calls to the Ingest method.
		Ingest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data io.Reader
			// Doer is the doer argument value.
			Doer func(key string, chunk *porter.Port) error
		}
	}
	lockIngest sync.RWMutex
}

// Ingest calls IngestFunc.
func (mock *IngestorMock) Ingest(ctx context.Context, data io.Reader, doer func(key string, chunk *porter.Port) error) error {
	if mock.IngestFunc == nil {
		panic("IngestorMock.IngestFunc: method is nil but Ingestor.Ingest was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data io.Reader
		Doer func(key string, chunk *porter.Port) error
	}{
		Ctx:  ctx,
		Data: data,
		Doer: doer,
	}
	mock.lockIngest.Lock()
	mock.calls.Ingest = append(mock.calls.Ingest, callInfo)
	mock.lockIngest.Unlock()
	return mock.IngestFunc(ctx, data, doer)
}

// IngestCalls gets all the calls that were made to Ingest.
// Check the length with:
//
//	len(mockedIngestor.IngestCalls())
func (mock *IngestorMock) IngestCalls() []struct {
	Ctx  context.Context
	Data io.Reader
	Doer func(key string, chunk *porter.Port) error
} {
	var calls []struct {
		Ctx  context.Context
		Data io.Reader
		Doer func(key string, chunk *porter.Port) error
	}
	mock.lockIngest.RLock()
	calls = mock.calls.Ingest
	mock.lockIngest.RUnlock()
	return calls
}
