// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package portsfromstream

import (
	"context"
	"porter"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			BatchCreateOrUpdatePortFunc: func(ctx context.Context, data map[string]*porter.Port) error {
//				panic("mock out the BatchCreateOrUpdatePort method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// BatchCreateOrUpdatePortFunc mocks the BatchCreateOrUpdatePort method.
	BatchCreateOrUpdatePortFunc func(ctx context.Context, data map[string]*porter.Port) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchCreateOrUpdatePort holds details about calls to the BatchCreateOrUpdatePort method.
		BatchCreateOrUpdatePort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data map[string]*porter.Port
		}
	}
	lockBatchCreateOrUpdatePort sync.RWMutex
}

// BatchCreateOrUpdatePort calls BatchCreateOrUpdatePortFunc.
func (mock *RepositoryMock) BatchCreateOrUpdatePort(ctx context.Context, data map[string]*porter.Port) error {
	if mock.BatchCreateOrUpdatePortFunc == nil {
		panic("RepositoryMock.BatchCreateOrUpdatePortFunc: method is nil but Repository.BatchCreateOrUpdatePort was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data map[string]*porter.Port
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockBatchCreateOrUpdatePort.Lock()
	mock.calls.BatchCreateOrUpdatePort = append(mock.calls.BatchCreateOrUpdatePort, callInfo)
	mock.lockBatchCreateOrUpdatePort.Unlock()
	return mock.BatchCreateOrUpdatePortFunc(ctx, data)
}

// BatchCreateOrUpdatePortCalls gets all the calls that were made to BatchCreateOrUpdatePort.
// Check the length with:
//
//	len(mockedRepository.BatchCreateOrUpdatePortCalls())
func (mock *RepositoryMock) BatchCreateOrUpdatePortCalls() []struct {
	Ctx  context.Context
	Data map[string]*porter.Port
} {
	var calls []struct {
		Ctx  context.Context
		Data map[string]*porter.Port
	}
	mock.lockBatchCreateOrUpdatePort.RLock()
	calls = mock.calls.BatchCreateOrUpdatePort
	mock.lockBatchCreateOrUpdatePort.RUnlock()
	return calls
}
