// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package getport

import (
	"context"
	"porter"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			GetPortFunc: func(ctx context.Context, unloc string) (*porter.Port, error) {
//				panic("mock out the GetPort method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// GetPortFunc mocks the GetPort method.
	GetPortFunc func(ctx context.Context, unloc string) (*porter.Port, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPort holds details about calls to the GetPort method.
		GetPort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unloc is the unloc argument value.
			Unloc string
		}
	}
	lockGetPort sync.RWMutex
}

// GetPort calls GetPortFunc.
func (mock *RepositoryMock) GetPort(ctx context.Context, unloc string) (*porter.Port, error) {
	if mock.GetPortFunc == nil {
		panic("RepositoryMock.GetPortFunc: method is nil but Repository.GetPort was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Unloc string
	}{
		Ctx:   ctx,
		Unloc: unloc,
	}
	mock.lockGetPort.Lock()
	mock.calls.GetPort = append(mock.calls.GetPort, callInfo)
	mock.lockGetPort.Unlock()
	return mock.GetPortFunc(ctx, unloc)
}

// GetPortCalls gets all the calls that were made to GetPort.
// Check the length with:
//
//	len(mockedRepository.GetPortCalls())
func (mock *RepositoryMock) GetPortCalls() []struct {
	Ctx   context.Context
	Unloc string
} {
	var calls []struct {
		Ctx   context.Context
		Unloc string
	}
	mock.lockGetPort.RLock()
	calls = mock.calls.GetPort
	mock.lockGetPort.RUnlock()
	return calls
}
